---
- hosts: all

  become: true

  tasks:
    - name: Install all security, critical, and rollup updates without a scheduled task
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups  

      - name: Ensure WinRM starts when the system has settled and is ready to work reliably
        win_service:
          name: WinRM
          start_mode: delayed

      - name: Ensure we wait long enough for the updates to be applied during reboot
        win_updates:
          reboot: yes
          reboot_timeout: 3600
